CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  website_url text,
  google_maps_link text,
  description text,
  bookable boolean,
  google_quotation double precision,
  google_review_total_value bigint,
  city text NOT NULL,
  address_line1 text,
  postal_code text,
  country_code text,
  latitude double precision,
  longitude double precision,
  instagram_url text,
  facebook_url text,
  whatsapp_phone text,
  phone text,
  email text,
  sponsored boolean,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id)
);
