create table public.restaurants (
  id uuid not null default gen_random_uuid (),
  name text not null,
  slug text null,
  address text null,
  created_at timestamp with time zone null default now(),
  website_url text null,
  google_maps_link text null,
  description text null,
  bookable boolean null,
  google_quotation double precision null,
  google_review_total_value bigint null,
  google_reviews_summary text null,
  city text not null,
  postal_code text null,
  country_code text null,
  latitude double precision null,
  longitude double precision null,
  instagram_url text null,
  facebook_url text null,
  whatsapp_phone text null,
  phone text null,
  email text null,
  sponsored boolean null,
  booking_url text null,
  afroliya_instagram_post_url text null,
  afroliya_instagram_thumbnail_url text null,
  commune text null,
  active boolean null default false,
  constraint restaurants_pkey primary key (id)
) TABLESPACE pg_default;